Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '25GB'
  config.vm.network "private_network", ip: "192.168.33.152"
  config.vm.hostname  = 'semantic'
  config.vm.provider "virtualbox" do |vb|
	  vb.memory=8096
	  vb.name  = 'semantic'
  end
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
end

